import "./globals.css";
import "./globals.css";
import type { Metadata } from "next";
import Providers from "@/components/Providers";
import Providers from "@/components/Providers";
import Navbar from "@/components/common/Navbar";
import { StepProvider } from "@/context/StepContext";

export const metadata: Metadata = {
  title: "DEX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-urbanist antialiased">
        <Providers>
          <div className="">
            <Navbar />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
